name: 'Auto Approve'
description: 'Automatically approve pull requests'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
