name: 'Auto Approve Dependabot'
description: 'Automatically approve dependabot pull requests'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  trusted-committers:
    description: 'Logins/IDs of committers that would be trusted for auto approval'
    required: false
    default: 'dependabot[bot],dependabot-preview[bot]'
  manage-approvals-for-reviewers:
    description: 'Logins/IDs of reviewers for which this action could manage their approvals'
    required: false
    default: 'github-actions[bot]'
runs:
  using: 'node12'
  main: 'dist/index.js'
