apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - path: vault.yaml
  - patch: |-
      - op: remove
        path: /spec/config/storage/inmem
    target:
      group: vault.banzaicloud.com
      version: v1alpha1
      kind: Vault
      name: vault
