nameOverride: ""
fullnameOverride: ""

# pass values to subcharts
global:
  provider: local  # choose from: local | aws | azure
  network: sepolia
  env: dev
  elc: besu
  clc: teku
  jwt:
    secretPath: "/jwt"
    hostAllowlist: ["*"]  
  snapshot:
    # sot (source of truth) node, ie this is what we will create snapshots of
    sot: false
    # use the defaults of hourly, daily, weekly
    schedule: "@weekly"

besu:
  restore:
    enabled: false
    # restore from a particular volumesnapshot
    snapshot: ""

teku:
  restore:
    enabled: false
    # restore from a particular volumesnapshot
    snapshot: ""
