name: Lint
on: [push]

jobs:
  build:
    name: Check style
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install

    - name: Check style with prettier
      run: npm run-script format-check

    - name: Check build artefact has been checked in
      run: npm run-script build && git diff
