name: Matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latst, windows-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - run: echo "${RUNNER_OS}"
          shell: bash
