name: Test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
   testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: sudo systemctl start postgresql.service ; pg_isready
      - run: cat db-migration/initdb.d/01_docker-bootstrap.sql | sudo -u postgres psql -f -
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87 # v3.0.0
        env:
          DATABASE_HOST: localhost
        with:
          arguments: check



